### ISSUE TITLE
ReadHandler for Domain and Repository should make policyDocument available

### ISSUE THREAD

**Issue by jonjara** [aws-cloudformation/aws-cloudformation-resource-providers-codeartifact#18]
**Is your feature request related to a problem? Please describe.**
Without it, `GetAtt` cannot get resource policy for resources

**Describe the solution you'd like**
Translator should populate `policyDocument` into the resource model using getPermissionPolicy APIs

**Comment by sankalpbhandari** [comment]
Users can set the `policyDocument` for domain and repository and is NOT a `readOnly` property . There seems to be no need to have these as part of `GetAtt`. Hence closing this issue.
