### ISSUE TITLE
Internal Failure due to incorrect registration instructions

### ISSUE THREAD

**Issue by OlafConijn** [aws-cloudformation/aws-cloudformation-resource-providers-codeartifact#33]
**Describe the issue**
After following the registration instructions on an AWS account that did not have the types registered prior creating a template results in 'internal failure'

**To Reproduce**
Follow registration instructions and create a resource on a fresh AWS Account
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact#register-a-codeartifact-repository-resource-provider-with-the-aws-cli

**Expected behavior**
The Registration instructions are wrong. the should include the registration of the [execution role](https://raw.githubusercontent.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/main/aws-codeartifact-domain/resource-role.yaml) and this should be passed when registering. [Similar to this example](https://github.com/org-formation/aws-resource-providers/blob/master/iam/password-policy/installation.md) 

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Comment by sankalpbhandari** [comment]
Looking into it.

**Comment by sankalpbhandari** [comment]
Closing this issue as instructions have been updated as part of https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/pull/35
