### ISSUE TITLE
Example JSON is incorrect

### ISSUE THREAD

**Issue by jonjara** [aws-cloudformation/aws-cloudformation-resource-providers-codeartifact#34]
**Describe the issue**
Sample template with `ExternalConnection` is incorrect

**To Reproduce**
Take this sample template: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/blob/main/sample-templates/json/create-repository-with-external-connection.json and the stack creation will fail

`ExternalConnection` should be `ExternalConnections`

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Comment by sankalpbhandari** [comment]
Closing this issue as sample template is fixed as part of https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/pull/35
