### ISSUE TITLE
Property descriptions are backwards

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/aws-cloudformation-resource-providers-codeartifact#4]
```json
    "AssetSizeBytes": {
      "description": "The current status of a domain. The valid values are",
      "type": "integer"
    },
    "Status": {
      "description": "The total size of all assets in the domain.",
      "pattern": "/^(Active|Deleted)$/",
      "type": "string"
    },
```

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/blob/master/aws-codeartifact-domain/aws-codeartifact-domain.json#L30-L37

Also, 'integer' for number of bytes in a domain feels like an integer overflow waiting to happen. What happens after 2.1GB?

**Comment by detam-amazon** [comment]
Description was fixed by Ian, but a response to the integer comment by Richard is still needed.

**Comment by detam-amazon** [comment]
AssetSizeBytes was removed, so no longer an issue
