### ISSUE TITLE
Create Only Properties

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/aws-cloudformation-resource-providers-codeartifact#5]
I assume that the Domain Name is a Create-Only property since it becomes part of the domain's ARN?

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/blob/master/aws-codeartifact-domain/aws-codeartifact-domain.json#L56

**Comment by jonjara** [comment]
https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-schema.html#schema-properties-createonlyproperties

**Comment by detam-amazon** [comment]
Addressed by #13
