### ISSUE TITLE
Accounts have IDs not numbers

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/aws-cloudformation-resource-providers-codeartifact#6]
[this section](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/blob/master/aws-codeartifact-domain/aws-codeartifact-domain.json#L14) should be 
```json
    "DomainOwner": {
      "description": " The 12-digit account ID of the AWS account that owns the domain.",
      "pattern": "[0-9]{12}",
      "type": "string"
    },
```
Leading zero have no meaning in a number, they do have a meaning in an account ID

**Comment by detam-amazon** [comment]
Addressed by Ian in #13 - closing issue
