### ISSUE TITLE
What is an Aspen?

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/aws-cloudformation-resource-providers-codeartifact#7]
Do you have docs for what is a 'valid' Aspen policy? This sounds like an AWS-ism

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/blob/master/aws-codeartifact-domain/aws-codeartifact-domain.json#L40

**Comment by detam-amazon** [comment]
That's one way to fix the problem!
